name: Shopping-Online with CI | © 2024 by binhNT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install GlassFish server
        run: |
          wget https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/5.1.0/glassfish-5.1.0.zip
          unzip glassfish-5.1.0.zip -d $GITHUB_WORKSPACE/glassfish5
          
      - name: Build project with Ant
        run: |
          wget -O copylibs.jar https://your-source-path/org-netbeans-modules-java-j2seproject-copylibstask.jar
          ant -noinput -buildfile build.xml -Dj2ee.server.home="$GITHUB_WORKSPACE/glassfish5/glassfish5" -Dlibs.CopyLibs.classpath="$GITHUB_WORKSPACE/copylibs.jar"

      - name: Verify build files
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls dist/*.jar 2>/dev/null)" ]; then
            echo "No build files found in 'dist'. Exiting."
            exit 1
          fi

      - name: Distribute jar-war file
        run: mkdir staging && cp dist/*.jar staging

      - name: Make hyperlink to jar-war file
        uses: actions/upload-artifact@v3
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging
